### ISSUE TITLE
Error in trymatch function

### ISSUE THREAD

**Issue by Arnolds-cat** [steven2358/Shazam-Matlab#3]
I'm trying to execute the tag_test code, but I'm having an error at line 51 of trymatch (index out of range for the array histo). Am I missing something? Thank you.

**Comment by steven2358** [comment]
This will need some debugging. I currently don't have access to a Matlab
installation but in about 10 days I can check this.

**Comment by Arnolds-cat** [comment]
Thank you very much.

**Comment by Arnolds-cat** [comment]
I've solved the problem by simply changing the songs file, so there was something wrong with the files I was using. Thank you.

**Comment by ahmetcangunay** [comment]
@Arnolds-cat Hi.
Could you please tell me how could you handle this problem? Because I have the same issue and I do not know how I can solve it.
